QA_Bluemix/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^items/', include('portal.urls', namespace="index")),
]

portal/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views
urlpatterns = [
    url(r'^$', views.index_view, name="index"),
    url(r'^(?P<product_id>[0-9a-zA-Z]+)/$', views.product_view, name='product'),

]

portal/models.py
from django.db import models

# Create your models here.

review_model_helper/models.py
from django.db import models


# Create your models here.
class Product(models.Model):
    id = models.CharField(max_length=10, primary_key=True)
    title = models.CharField(max_length=100, null= True, blank= True)
    description = models.CharField(max_length=500, null= True, blank= True)

    def __str__(self):
        return self.title


class ProductReviews(models.Model):
    product_id = models.ForeignKey(Product)
    review_text = models.CharField(max_length=1000, null=False, blank=False)

    def __str__(self):
        return self.review_text[:25]

portal/forms.py
from django import forms


class QuestionForm(forms.Form):
    question = forms.CharField(label='question',
                               max_length=150,
                               required=True)

portal/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseNotFound
from portal.forms import QuestionForm
from portal.Constants import *
import requests
import nltk
import json
from nltk.stem.wordnet import WordNetLemmatizer
from review_model_helper.models import ProductReviews, Product
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from portal.paraSumm import summarize
import re
from django.core.exceptions import ObjectDoesNotExist


def get_product_reviews(product_id):
    reviews = ProductReviews.objects.filter(product_id=product_id)
    document = ''.join([review.review_text for review in reviews])
    return document


def req_rank_retrieve(qn, product_id):
    params['text'] = qn
    r = requests.get(ALCHEMY_URL, params=params)
    data = r.json()
    keyWords=[]
    try:
        for dt in data['keywords']:
            keyWords.append(dt['text'])
    except KeyError:
        print("KeyError")
    print("keywords, ", keyWords)
    if len(keyWords) == 0:
        # if there are no keywords in a question, this function can terminate.
        return None
    lemmatizer = WordNetLemmatizer()
    document = get_product_reviews(product_id)
    sentences = nltk.sent_tokenize(document)
    document = []
    for sent in sentences:
        sent_list = []
        for word in nltk.word_tokenize(sent):
            sent_list.append(word)
        document.append(sent_list)
    answers = []
    and_sent = set()    # to store sentence index whose keywords were matched.
    for sent_i in range(0, len(document)):
        sent = document[sent_i]
        # lemmatization check as well.
        sent_lemma = []
        for st in sent:
            sent_lemma.append(lemmatizer.lemmatize(st))
        for keyword in keyWords:
            if lemmatizer.lemmatize(keyword) in sent_lemma:
                and_sent.add(sent_i)
    for s_id in and_sent:
        answers.append(' '.join(document[s_id]))
    # print(answers)
    answers = ''.join(answers)
    summarized_answer = ''.join(summarize(answers))
    summarized_answer = re.sub('[^a-zA-Z0-9\s\.]', '', summarized_answer)
    print("summarized answer ", summarized_answer)
    if len(summarized_answer) == 0:
        return None
    return summarized_answer


def product_view(request, product_id):
    try:
        product = Product.objects.get(pk=product_id)
    except ObjectDoesNotExist:
        return HttpResponseNotFound("<h1>Page not found</h1>")
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            qn = form.cleaned_data['question']
            answers = req_rank_retrieve(qn, product_id)
            return render(request, 'portal/answer.html', {'answers': answers, 'product_id': product_id, 'qn': qn})
    else:
        form = QuestionForm()

    return render(request, 'portal/product.html', {'form': form, 'product_id': product_id, 'product': product})


def index_view(request):
    product_list = Product.objects.all()
    paginator = Paginator(product_list, 25) # Show 25 contacts per page

    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        products = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        products = paginator.page(paginator.num_pages)

    return render(request, 'portal/index.html', {"products": products})

review_model_helper/views.py
from django.shortcuts import render

# Create your views here.

portal/templates/portal/answer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Answer</title>
</head>
<body>
<p>{{qn}} </p>
{% if answers != None and qn|length != 0%}
<p>{{ answers }}</p>
{% else %}
<p>Result is zero.</p>
{% endif %}
<a href="{% url 'index:product' product_id %}">New Question?</a>
</body>
</html>

portal/templates/portal/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
</head>
<body>

{% for product in products %}
<a href="{% url 'index:product'  product.id %}"><p>{{ product.title }}</p></a>
{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if contacts.has_previous %}
            <a href="?page={{ contacts.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ contacts.number }} of {{ contacts.paginator.num_pages }}.
        </span>

        {% if contacts.has_next %}
            <a href="?page={{ contacts.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>


</body>
</html>

portal/templates/portal/product.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Answer</title>
</head>
<body>
<h2>{{product.title}}</h2>
<p>{{product.description}}</p>
<form action="{% url 'index:product' product_id %}" method="post">
    {% csrf_token %}
    {{form}}
    <button type="submit">Search</button>
</form>
</body>
</html>